project:
  type: website
  title: "ICIODSS (24/25)"
  output-dir: docs

website:
  title: "ICIODSS (2024/25)"
  page-navigation: true
  sidebar:
    style: floating
    contents:
      - href: index.qmd
        text: Introduction
      - section: "This Course"
        contents: 
          - href: description.qmd
            text: Description
          - href: schedule.qmd
            text: Schedule
      - text: -------
      - section: "Week 1: Introduction and Fundamental Concepts"
        contents: 
          - href: week1_literature.qmd
            text: "Literature"
          - href: week1_lab.qmd
            text: "Lab exercises"
      - section: "Week 2: Directed Acyclical Graphs"
        contents: 
          - href: week2_literature.qmd
            text: "Literature"
          - href: week2_lab.qmd
            text: "Lab exercises"
      - section: "Week 3: Rubin Causal Model (Part I)"
        contents:
          - href: week3_literature.qmd
            text: "Literature"
          - href: week3_lab_noAnswers.qmd
            text: "Lab exercises"
      - section: "Week 4: Rubin Causal Model (Part II)"
        contents:
          - href: week4_literature.qmd
            text: "Literature"
          - href: week4_lab_noAnswers.qmd
            text: "Lab exercises"
      - section: "Week 5: MSMs and Time-Varying Exposures"
        contents: 
          - href: week5_literature.qmd
            text: "Literature"
          - href: week5_lab_noAnswers.qmd
            text: "Lab exercises"
      - section: "Week 6: Estimating Causal Effects of Time-Varying Exposures"
        contents:
          - href: week6_literature.qmd
            text: "Literature"
          - href: week6_lab_noAnswers.qmd
            text: "Lab exercises"
      - text: -------
      - href: assignment.qmd
        text: "Assignment"
            
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



