---
title: "Description"
editor: source
---

In psychology and related disciplines, researchers commonly ask causal questions, albeit oftentimes implicitly so. For example, psychologists might be interested in how light physical activity might *reduce* depressive symptoms, if lower pay in a profession *leads to* fewer men choosing this profession, or if satisfaction with one's social contacts *affects* self-esteem. While a randomized controlled trial (RCT) is considered the golden standard for studying such questions, there are often practical or ethical constraints that prohibit us from doing so, and researchers have to resort to using observational (i.e, nonexperimental) data. 

To answer causal questions using observational data, we need to be extremely clear about what our causal question is, think carefully about what data we need for identifying it, and make an informed decision about which analysis techniques allows us to draw the most robust conclusions. This course provides you with an introduction to this formal causal research process. You will get acquainted with the basic building blocks of modern causal inference, learn about the steps and assumptions that need to be made throughout a study, and apply various estimation techniques to simulated and empirical (i.e., real-world) observational data. We start with introducing the causal inference building blocks like potential outcomes and directed acyclical graphs (DAGs) from a cross-sectional perspective (i.e., in which all variables have only been measured once). In the second halve of the course, we will apply these building blocks to a longitudinal settings. This allows us to ask new types of interesting causal questions, but also presents new challenges. 

The causal inference literature provides enough material to fill an entire two-year master program, and we will only scratch the surface of the most important topics therein. Therefore, the goal of the course is (a) provide a motivation for the importance of robust causal inference in much of the modern psychological literature; (b) to introduce you to fundamental concepts of causal inference, and (c) for you to get hands-on experience with the causal research process for observational data. After this course, you can start applying some of these techniques yourself to observational data, and you can critically evaluate (implicitly) causal studies in psychology and related disciplines. 