---
title: "Syllabus"
bibliography: references.bib
editor: source
---

You can find the course schedule in the overview below. Lectures and labs will take place in the Wolfgang-Köhler-Haus (Rudower Chaussee 18), room 2.101 (Testbibliothek).  


| Week | What    | Topic                                 |
|------|---------|---------------------------------------|
| 43   | Reading | @hernan_c-word_2018                   | 
|      | Lecture | Introduction and fundamental concepts | 
|      | Lab     | Exercises                             |
| 44   | Reading | @rohrer_thinking_2018                  |
|      | Lecture | Causal graphs                         |
|      | Lab     | Exercises                             |
| 45   | Reading | @schafer_average_2008                 |
|      | Lecture | Rubin Causal Model (Part I)           |
|      | Lab     | Exercises                             |
| 46   | Reading | @schafer_average_2008                 |
|      | Lecture | Rubin Causal Model (Part II)          |
|      | Lab     | Exercise, start assignment            |
| 47   | Reading | @vanderweele_causal_2016              |
|      | Lecture | Marginal Structural Models and time-varying exposures |
|      | Lab     | Exercises                             |
| 48   | Reading | @mulder_causal_2024                   |
|      | Lecture | Estimating causal effects of time-varying exposures |
|      | Lab     | Exercises                             |
| 49   | Lab     | Assignment: Preparation               |
| 50   | Lecture | Assignment: Presentations             | 
